### ISSUE TITLE
local-typescript-operations breaks with visitor-plugin-common >= 2.8.0

### ISSUE THREAD

**Issue by mvarendorff** [atmina/graphql-codegen-plugins#1]
visitor-plugin-common@2.8.0 renamed buildSelectionSetString to buildSelectionSet breaking the super call here:

https://github.com/atmina/graphql-codegen-plugins/blob/a140ce01ffbc08d6c8ade0417deda98d80b08e8b/plugins/local-typescript-operations/src/index.ts#L480

The commit in which the function was changed:

https://github.com/dotansimha/graphql-code-generator/commit/f1fb77bd45dbb0b332066d096577552b88d76949

The following used dependencies have visitor-plugin-common >= 2.8.0 as dependency:

@graphql-codegen/typescript: ^2.0.0 (should be >=2.0.0 <=2.4.10)
@graphql-codegen/typescript-operations: ^2.0.0 (>=2.0.0 <=2.3.7)

**Comment by mvarendorff2** [comment]
Support for `@graphql-codegen/visitor-plugin-common@>=2.8.0` was added in version `0.6.0` of the `local-typescript-operations` plugin.
